### ISSUE TITLE
Convert script

### ISSUE THREAD

**Issue by lovelxc** [binarly-io/guiddb#2]
Can you please provide a script to convert from CSV to JSON? Thx a lot!

**Comment by yeggor** [comment]
probably this script is something you need: https://gist.github.com/yeggor/9a28660a83121e52cff7416f643e9570

**Comment by lovelxc** [comment]
> this script is probably something you need: https://gist.github.com/yeggor/9a28660a83121e52cff7416f643e9570

Thanks!!
